### ISSUE TITLE
Online compiler fails for Firefox, but works for Chrome (in Ubuntu)

### ISSUE THREAD

**Issue by artella-coding** [melsman/mlkit#1]
Hi, I was trying the online IDE at https://smlserver.org/ide/ but I am having problems compiling the example at `Server/Examples/life.sml` in Firefox (Ubuntu 64 bit). When I try to compile it I get the error message :

```
[Loading Basis Library .load_env problem: InternalError: too much recursion
```

Strangely this particular example runs fine in Chrome.

**Comment by melsman** [comment]
I'm closing this issue as the error has gone away by itself...
