### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by fxcoudert** [melsman/mlkit#115]
Compiling mlkit on Apple Silicon (macOS with an ARM processor) leads to an error because of Intel-specific asm at https://github.com/melsman/mlkit/blob/d5619c2635d9c799e31e572b58a47f1ee3b6c09e/src/Runtime/Region.c#L792

Is mlkit Intel-only?

**Comment by melsman** [comment]
Yes - currently it is x86_64 only... The code generator generates x86_64 assembler...
