### ISSUE TITLE
REPL? 

### ISSUE THREAD

**Issue by entrust1234** [melsman/mlkit#123]
Hello, 

Does MLKit have a REPL?

**Comment by melsman** [comment]
No. MLKit does not feature a repl.

**Comment by entrust1234** [comment]
Ok, thanks for the reply.

**Comment by melsman** [comment]
It would be great with a REPL. I have some ideas about how such a thing can be constructed, based on the current infrastructure, but it would require some work on (and inderstanding of) dynamically linking code generated by MLKit - perhaps a good fit for an MSc project...

**Comment by melsman** [comment]
See #138

**Comment by melsman** [comment]
Resolved by #138.
