### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by jeremydaw** [melsman/mlkit#128]
As indicated in README.md, I tried to run 'make install', however I got the following

[jeremy@tc-m72e mlkit]$ make install
make install0
make[1]: Entering directory '/home/jeremy/mlkit'
./mkinstalldirs /home/jeremy/mlkit
./mkinstalldirs /home/jeremy/mlkit/bin
/usr/bin/install -c bin/mlkit /home/jeremy/mlkit/bin
/usr/bin/install: 'bin/mlkit' and '/home/jeremy/mlkit/bin/mlkit' are the same file
make[1]: *** [Makefile:216: install0] Error 1
make[1]: Leaving directory '/home/jeremy/mlkit'
make: *** [Makefile:246: install] Error 2

**Comment by melsman** [comment]
Does this issue still persist? There are multiple places in the `README.md` file that mention `make install`. Which instance is problematic? Please provide a full error log...

**Comment by melsman** [comment]
Closing this issue as it cannot be reproduced...
