### ISSUE TITLE
Error compiling using mlkit.

### ISSUE THREAD

**Issue by wpoosanguansit** [melsman/mlkit#13]
Hi,

I installed mlkit on Unbuntu 16 on x86_64 platform.  I managed to install mlkit from source and got the command in my path.  However when i ran

➜  Repl mlkit main.mlb
[wrote X86 code file:   MLB/RI_GC/base-link_objects.s]
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
[wrote executable file: run]

➜  ~ mlkit -v
MLKit 4.3.9 (2017-06-24T-04:08:07) [X86 Backend]

I have got the error above.  How do I make the install x86_64 instead of x86_32?  Thanks for your help.

**Comment by melsman** [comment]
It is not currently possible to have the mlkit generate 64bit machine code... Quite a few changes would be requirred to support 64bit machine code including changes to the code generator and to the runtime system...
