### ISSUE TITLE
Running MLKit on alpine

### ISSUE THREAD

**Issue by ii8** [melsman/mlkit#140]
I'm trying to use the mlkit compiler in a regular alpine:latest docker container. MLKit is not available from alpine repositories so I'm trying to use the binary releases since I have no way to build from source on alpine. But there seems to be a problem with the binary distribution for linux, when trying to run mlkit it reports:
```
/bin/sh: mlkit: not found
```
And ldd reports:
```
$ ldd /usr/local/bin/mlkit
        /lib64/ld-linux-x86-64.so.2 (0x7ff03e050000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7ff03e050000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x7ff039a50000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7ff03e050000)
Error relocating /usr/local/bin/mlkit: __fprintf_chk: symbol not found
Error relocating /usr/local/bin/mlkit: __vfprintf_chk: symbol not found
Error relocating /usr/local/bin/mlkit: __snprintf_chk: symbol not found
```
So it looks like the binary distribution is dymanically linked which stops it from working on systems that don't use the same shared libraries.

I have tried packaging mlton and mlkit for voidlinux as well which is also proving to be a little challenging because no static and/or musl based binary distribution is available for bootstrapping.

So would it be possible to change or add to the linux binary distribution so it is statically linked (ideally with musl to save space) so that it works on any linux system?

**Comment by melsman** [comment]
The binary package, including the embedded `mlkit` executable is built with MLton (`mlton`), which is responsible for not creating a fully statically linked executable. I have no experience with using musl (or alpine), but I believe it should be possible to cross-compile somehow. To do so, we need (at least) to link to a runtime system compiled with `musl-gcc` and the basis library linked with `musl-gcc`.

**Comment by melsman** [comment]
It is possible to pass the flag `-link-opt '-static'` to `mlton` to create a statically linked `mlkit` executable, but I don't know if this is a good choice for the general binary package.

**Comment by MatthewFluet** [comment]
> It is possible to pass the flag `-link-opt '-static'` to `mlton` to create a statically linked `mlkit` executable, but I don't know if this is a good choice for the general binary package.

Yes.  For the next MLton release (who knows when), I plan to build both dynamically and statically linked packages, the latter primarily for these bootstrapping scenarios.

**Comment by ii8** [comment]
> I plan to build both dynamically and statically linked packages, the latter primarily for these bootstrapping scenarios.

It's unclear how feasible it is to build a truly static mlton, because even if the executable mlton-compile is static, the programs it generates still rely on libc (even if they themselves are also being statically linked, they still need libc at link time)

To be entirely self-contained a mlton would probably have to almost ship a little toolchain

**Comment by athas** [comment]
I have good experiences dynamically linking glibc (although it is usually considered a bad idea).  It will work fine *except* for name lookups (DNS), where glibc depends on dynamic linking.  Since I don't think mlkit does any DNS lookups when compiling SML programs (or even any network traffic at all), it should work fine.

**Comment by athas** [comment]
Yes.  Fixing that typo.

**Comment by melsman** [comment]
Another question is whether we can assume that some version of libc is available for dynamic linking when mlkit is invoked on the target platform - the new REPL, which of course can be disa led, makes extensive use of dynamic linking...

**Comment by athas** [comment]
You cannot assume any version of glibc, but note that all of this only applies to the `mlkit` executable *itself*.  When using the REPL, all code is effectively JIT-compiled on the target platform, so you can dynamically link without trouble.

Having a statically linked `mlkit` executable has no implications on the linkage of the code it generates.  Unless the REPL works by linking the `mlkit` *executable* with the user-written code (which is nonsensical and certainly not what you do), then these are orthogonal concerns.

**Comment by athas** [comment]
[musl does not support dlopen()](https://git.musl-libc.org/cgit/musl/tree/src/ldso/dlopen.c) so the REPL will certainly not work on a musl system, but the compiler itself ought to work.

**Comment by melsman** [comment]
... but the statically linked runtime system is linked with a version of glibc and the runtime system contains calls to glibc's dlopen and friends. It uses those calls to implement the REPL server command loop, which loads in code dynamically and executes it...

**Comment by athas** [comment]
Then I guess it might work.  But you have to be very careful when you compile the C program that constitutes the REPL.

**Comment by melsman** [comment]
Generating fully statically linked executables does not seem possible on macOS.

**Comment by ii8** [comment]
It's now possible to run MLKit on alpine by building from source using a MLton from https://github.com/ii8/mlton-builds so this issue can be closed from my perspective.

**Comment by ii8** [comment]
> Generating fully statically linked executables does not seem possible on macOS.

AFAIK building static executables isn't all that useful for macOS anyway because the userspace environment is much more consistent than linux(there isn't multiple different libcs) and it doesn't have as stable a kernel abi like linux.

**Comment by melsman** [comment]
> It's now possible to run MLKit on alpine by building from source using a MLton from https://github.com/ii8/mlton-builds so this issue can be closed from my perspective.

Great! I'll also attempt to generate statically linked Linux executables for future releases.
