### ISSUE TITLE
MLKit's REPL crashes when ran outside of the project directory

### ISSUE THREAD

**Issue by DarinM223** [melsman/mlkit#152]
MLKit's REPL seems to load some library files relative to the current working directory. This means that if the REPL is ran from a different folder than the directory that MLKit was built in, then it crashes with this error:

```
MLKit v4.7.5 (v4.7.5-4-g8a083920 - 2023-11-08T00:56:22+01:00) [X64 Backend]
|Garbage collection disabled - it is not supported in the REPL!
|Type :help; for help...
Repl.load.dlopen: Error openening MLB/RI/libstdin-16-0.so: MLB/RI/libstdin-16-0.so: undefined symbol: ptr_hitag_clear_funKilled
```

https://github.com/melsman/mlkit/blob/0415490362865b3f23a28abe37d08356b41c812f/src/Runtime/Repl.c#L401-L402

**Comment by melsman** [comment]
Hmm - maybe MLKit tries to use an older version of the runtime system. How did you install MLKit v4.7.5 and how was it invoked? Perhaps you have an `.mlkit/mlb-path-map` file lying around that confuses MLKit!?

**Comment by DarinM223** [comment]
It seems that there were `MLB` folders in the directories I ran the REPL in that had the older runtime libraries. It worked in the project directory because it had a newer version of the runtime.

On my [fork](https://github.com/DarinM223/mlkit/tree/repl_env) I am adding an environment variable path that the REPL can use to create and read the REPL library files in. This should prevent me from having problems where different folders have different versions of the REPL files.
