### ISSUE TITLE
Autoconversion of Int64.int

### ISSUE THREAD

**Issue by athas** [melsman/mlkit#153]
My company has the following critical business logic in a C function:

```C
#include <stdint.h>

int64_t cadd(int64_t x, int64_t y) {
  return x + y;
}
```

I would very much like to be able to access it from SML.  When I do

```SML
fun cadd (x: Int64.int, y: Int64.int) : Int64.int =
  prim ("@cadd", (x, y))
```

I get

```
Impossible: ClosExp:tn_to_foreign_type.Type name int64 not supported in auto conversion
Impossible: ClosExp:CCALL_AUTO.zip
[[ERR in sub process:
  CRASH]]
```

Would it be possible to add support for autoconversion of 64-bit integers?  I am aware that this involves boxing the return value.  That is fine with me.

**Comment by athas** [comment]
Actually, my company has critical business logic in C functions that return and accept *all* primitive types (`int8_t`, `int16_t`, `int32_t`, `int64_t`, and the unsigned variants, as well as `double` and `float`).  It would be delightful if they all just worked with auto conversion.

**Comment by athas** [comment]
Yes, that would be very nice.  If you also add autoconversion for e.g. `Word8Array.array`, then pretty much all C interaction can be done via glue code.

**Comment by melsman** [comment]
Partly fixed by PR #154.

**Comment by athas** [comment]
Nice!  That is just what I need.  I think it is fine (and expected) that array lengths are not implicitly passed as well - you can always do that from the SML side.  I will give this a try.

**Comment by athas** [comment]
It would also be nice to have autoconversion of any type `t ref`, where `t` is an autoconvertable type.  On the C side, this would be a pointer to the raw data.  For example, `Int64.int ref` would become `int64_t*` and `foreignptr ref` would become `void*`.  I am aware this is perhaps a bit complicated, as e.g. an `int ref` might not actually involve an `int` in C-readable format stored anywhere, as it will have tag bits.  But it would be mighty useful if the compiler would generate the necessary boilerplate to make it work!  If so, the MLKit FFI would have pretty close feature parity with that of MLton.
