### ISSUE TITLE
undefined reference to `equalPolyML'

### ISSUE THREAD

**Issue by athas** [melsman/mlkit#160]
I get this error during linking when running `make run_test_mlkit` on [smlfut](https://github.com/diku-dk/smlfut) (requires Git version of Futhark as well).  I can provide the generated file if desired, but I think I know what is going wrong.

I compile with `-no_gc`, which means that MLKit uses the runtime system without a tagged representation, and in particular without the `equalPolyML` function.  Yet, when I define the following datatype, MLKit seems to generate code that makes use of `equalPolyML`:

```SML
      datatype sum_opaque =
        bar of record.t
      | baz of Int32Array1.array * Bool.bool
      | foo of Int32.int
```

Here both `record.t` and `Int32Array1.array` are simply tuples (and not even abstract) containing `foreignptr`s.  If I change the datatype as follows, the bug disappears:

```SML
      datatype sum_opaque =
        bar of (bool -> bool) * record.t
      | baz of Int32Array1.array * Bool.bool
      | foo of Int32.int
```

I suspect the issue is related to the generation of automatic equality functions, as inserting the `bool->bool` value forces the type to be not an equality type.

I can also make `record.t` abstract (and not an eqtype), which I may do as a workaround in this case.

**Comment by athas** [comment]
Actually, scratch that - the workaround doesn't work.  The error occurs even after making `record.t` abstract (but the trick of jamming a function in there does work).

**Comment by athas** [comment]
[These](https://github.com/melsman/mlkit/blob/a312f16472e65a8f09bf0c79380d9e0824d3b9cc/src/Compiler/Backend/ClosExp.sml#L2257-L2261) are the only places where uses of `equalPolyML` are emitted.

**Comment by melsman** [comment]
It is an error for MLKit to emit calls to the equalPolyML function (eith or without gc) - for foreignptr's, we should emit pointer equality tests instead...

**Comment by athas** [comment]
As by our discussion today, the best fix for this is to just implement equality of foreignptr.  It's sometimes useful and the semantics are sensible.
