### ISSUE TITLE
Example of Javascript invoking SML

### ISSUE THREAD

**Issue by artella-coding** [melsman/mlkit#2]
Hi, on the homepage of http://www.smlserver.org/smltojs/ it mentions :

    JavaScript integration. SMLtoJs has support for calling JavaScript functions and for executing plain     JavaScript. Moreover, Standard ML functions may be exported and called by JavaScript code.

Is there an example of this anywhere in `https://github.com/melsman/mlkit`? Thanks

**Comment by melsman** [comment]
To use existing Jacascript libraries together with SmlToJs, the programmer should use the JsCore library... There is currently no example demonstrating the possibility of using functionality written in SML from Javascript.
