### ISSUE TITLE
smltojs generates wrong output

### ISSUE THREAD

**Issue by Munksgaard** [melsman/mlkit#22]
The following code produces incorrect javascript:

```sml
local
fun memoize (f : 'a -> 'b) : 'a -> 'b =
    let val r : unit list ref = ref []
    in fn x => f x
    end

fun test x = x

val test = memoize (fn x => x) test
in
val () = ()
end
```

**Comment by Munksgaard** [comment]
A simpler case that generates the same error:

```sml
fun bar x =
    fn x => ()

fun foo () =
    (bar (Real.fromString "4.0"); ())

val () = foo ()
```

The resulting code is a bit longer, but perhaps the problem is easier to understand with this code.

**Comment by nrnrnr** [comment]
I have production code that is getting clobbered by this same error.  I'm getting syntactically incorrect JavaScript with the message "SyntaxError: Function statements require a function name."

@kfl @melsman is there a chance you could have a look?  @Munksgaard did you find a workaround?
