### ISSUE TITLE
System Freeze During Compilation

### ISSUE THREAD

**Issue by BurningTire** [melsman/mlkit#24]
Hello,
in the installation instructions it mentions successfully compiling MLKit with MLton on a system with 3GB, but on my system that has 6GB of RAM, running `make` eventually causes my system to completely freeze and become unresponsive.  I'm running Arch Linux and am using the version of MLton from the official repository.
I understand that MLton is RAM hungry, but since the README mentions a successful compilation on a 3GB system, I shouldn't be running out of memory on a 6GB system.
The steps I followed were:

-  `$ git clone https://github.com/melsman/mlkit.git`
-   `$ cd mlkit`
-  `$ ./autobuild`
-  `$ ./configure --prefix=$HOME/.local/bin/mlkit`
-  `$ make`

I'd really like to be able to compile MLKit, so any help with this issue is much appreciated.

**Comment by BurningTire** [comment]
Tried compiling again without any other programs open, and luckily it worked this time and hardly used any memory to do so (much less than GHC a lot of the time), so I'm going to close this.  I actually ran `make bootstrap` before I tried running `make` last time, so I'm fairly certain that's what caused `make` to eat up a grip of memory and freeze my system.

**Comment by melsman** [comment]
Good to hear. An alternative is to bootstrap using a binary mlkit package -
either from brew ot using

https://code.launchpad.net/~pmunksgaard/+junk/mlkit-package

tir. 30. okt. 2018 kl. 05.06 skrev BurningTire <notifications@github.com>:
