### ISSUE TITLE
Barry install target by default deletes /usr/local

### ISSUE THREAD

**Issue by cannam** [melsman/mlkit#27]
`Makefile.in` target `install_barry` at line 474:

```
	rm -rf $(INSTDIR_BARRY)
```

By default `$(INSTDIR_BARRY)` is `/usr/local`, so this is probably not what most people want. It was certainly surprising to me!

I see that the `install_kam` target above has the same line in it.

Removing this line is also not enough to make the target succeed, because it also uses the undefined `$(ARCH-OS)`.

**Comment by melsman** [comment]
Fixed by #41 - although barry is not in general in a good shape...
