### ISSUE TITLE
building mlkit fails to terminate

### ISSUE THREAD

**Issue by jeremydaw** [melsman/mlkit#3]
mlton @MLton ram-slop 0.7 -- -drop-pass deepFlatten -drop-pass refFlatten -output mlkit Compiler/native.mlb
^Cmake[1]: *** [mlkit_kit] Interrupt

the step above seems to go on for ever - unless it's supposed to take a terribly long time (how long?) then something is wrong.

Using latest mlkit sources off github and 
[jeremy@localhost mlkit]$ rpm -q mlton
mlton-20130715-4.fc20.x86_64

**Comment by melsman** [comment]
Yes - using Mlton to compile Mlkit takes a lot of time - upto 20 minutes on
a modern machine, and no notifications of progress; you may run 'top' to
see when Mlton invokes the assembler... Make sure you have at least 4gb ram
on your machine...

Best, Martin

Den onsdag den 23. december 2015 skrev jeremydaw <notifications@github.com>:

**Comment by MatthewFluet** [comment]
You could add a `-verbose 2` to the MLton invocation to see the progress of the compilation.

**Comment by jeremydaw** [comment]
That's fine, thanks - all it needed was patience
