### ISSUE TITLE
https://smlserver.org/ide/

### ISSUE THREAD

**Issue by david-topham** [melsman/mlkit#48]
This is a wonderful project!  Lot's of hidden gems in the source that demo things like html, DOM, web reactive programming, etc.  A bit hard to figure out how to use some the APIs though. Is there any documentation for that?
Also on how to connect online server to (my) dropbox so I can save files?

**Comment by melsman** [comment]
Unfortunately, Dropbox has discontinued the version of their API used,
which means that it is no longer possible to save files... I haven't gotten
around to fix this yet, unfortunately...

man. 13. jul. 2020 kl. 16.55 skrev David Topham <notifications@github.com>:

**Comment by david-topham** [comment]
Thank you for your response. Perhaps the export/import project could be enough.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by melsman** [comment]
It now works with Dropbox again - but you need to load the system from https://diku-dk.github.io/sml-ide/ ...
