### ISSUE TITLE
Overflow integer

### ISSUE THREAD

**Issue by david-topham** [melsman/mlkit#49]
I really enjoy this project!  I just discovered though that there is no indication (that I see right now) of how to detect integer overflow.  e.g.  This code:
fun factorial 0 = 1  | factorial n = n * factorial(n-1); 
fun P(n,r) = (factorial n) div (factorial (n-r));
fun C(n,r) = P(n,r) div (factorial r);
P(12,3);  C(12,3);
P(13,3);  C(13,3);

...works fine, but after converting to js I get incorrect answer once I make n larger than 12. I know that is because of 32-bit integer overflow, but what is best (or is there a) way to tell smltojs to implement it with 64-bit integer?
i.e.  so we don't need to restrict range or at least let user know...[https://david-topham.github.io/smltojs/doc/dmfp-7-11-js.html](url)

**Comment by melsman** [comment]
The native MLKit uses 64bit, but SMLtoJs compiles integers to 32-bit entities. SMLtoJs ensures that the Overflow exception is raised in case of overflow. You can verify this property by compiling and running your code with https://diku-dk.github.io/sml-ide/ . There are no plans for providing 64-bit support for SMLtoJs; Perhaps you can use the `IntInf` module instead...

**Comment by david-topham** [comment]
Thank you, I will try that approach.



________________________________
