### ISSUE TITLE
Expose Word16

### ISSUE THREAD

**Issue by athas** [melsman/mlkit#67]
16-bit unsigned numbers are a cool new datatype that are pretty handy for many applications.  I think MLKit should expose these by default.  Word8 might be cool, too.

**Comment by melsman** [comment]
Word8 is available in the basis and so is Word8Array, Word8Vector, Word8ArraySlice, and Word8VectorSlice...

**Comment by athas** [comment]
Sorry, didn't notice.  But I need twice as many bits!

**Comment by melsman** [comment]
Is it only the Word16 structure you need?

man. 22. feb. 2021 kl. 15.54 skrev Troels Henriksen <
notifications@github.com>:

**Comment by athas** [comment]
Yes, but you really should consider exposing `Word32` and `Word64` as well, since it's just a matter of time until someone needs to implement an algorithm that uses these primitives.

**Comment by melsman** [comment]
They are exposed already including Word64ArraySlice et al...

man. 22. feb. 2021 kl. 16.43 skrev Troels Henriksen <
notifications@github.com>:

**Comment by melsman** [comment]
Solved partly by #68 . Currently, there is no support for overloading of constants and operations on Word16.word values.

**Comment by melsman** [comment]
We will leave up to a future PR to implement overloading for `Word16.word` values and for giving support for `Word16Array` and friends.
