### ISSUE TITLE
Operation for detecting the number of cores

### ISSUE THREAD

**Issue by melsman** [melsman/mlkit#69]
We need an operation for detecting the number of cores on the host machine. 

@athas has some C code we can use (we need support for both Linux and macOS).

The idea would be to include an operation

    val numCores : unit -> int

in the `Thread` structure.

**Comment by athas** [comment]
[This is the code](https://github.com/diku-dk/futhark/blob/819e5b3dff76dfa8d98deacb8a64dc295ffd87a9/rts/c/scheduler.h#L137-L159).
