### ISSUE TITLE
Trouble building on 64 bit ubuntu / coming up with a Dockerfile

### ISSUE THREAD

**Issue by rrnewton** [melsman/mlkit#8]
A Dockerfile would represent a simple and complete recipe to build in a modern 64 bit Linux environment.  I tried this:

```
FROM ubuntu:12.04
RUN apt-get update && apt-get install -y gcc mlton
RUN apt-get install -y autoconf make
ADD . /mlkit
RUN cd /mlkit && ./autobuild && ./configure && \
   make mlkit && make bootstrap && make mlkit_libs
```

Placed within a checkout of the mlkit repo.  But on ubuntu 12.04, 14.04, and 16.04, the above always fails with an error like the following:

```
gcc -m32 -o rp2ps Rp2Ps.o ProfileData.o Sample.o Graph.o Curves.o Output.o PostScript.o Error.o Alloc.o -lm
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find -lm
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.6/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.6/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.6/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.6/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: ld returned 1 exit status
make[2]: *** [rp2ps] Error 1
```

More work is needed to make it build in 32 bit mode, it seems, but I don't yet have the answer. 

Help coming up with a 64 bit build recipe would be appreciated.

**Comment by melsman** [comment]
Yes - that would be great.. There is a 32bit mlkit vagrant image available
from https://atlas.hashicorp.com/melsman/boxes/ubuntu_1404_i686_mlkit

>

**Comment by MatthewFluet** [comment]
The errors look like the typical errors when compiling with `-m32` but not having 32-bit multilib installed.

**Comment by rrnewton** [comment]
Thanks @MatthewFluet, including `gcc-multilib` worked fine.

It works fine now and I made a pull request: https://github.com/melsman/mlkit/pull/9

**Comment by melsman** [comment]
... and it has already been merged ;) Thanks!

>
