### ISSUE TITLE
Compilation error: operand type mismatch for push

### ISSUE THREAD

**Issue by willghatch** [melsman/mlkit#84]
Here is a program I found fuzzing mlkit that crashes the compiler, but works for other SML implementations I've tried it with:

```
fun main() = let

  fun nth_wrap(l, _, fallback) = if false
    then fallback
    else let val i = (0 mod (List.length l)) in List.nth(l, i) end

  val part1 = (nth_wrap([(size(""))], 0, ~1073741825))  
  val part2 = (nth_wrap(([ 0 ]), 0, 0))
in print "\n"
end
val _ = main()
```

I've tried to minimize it as best I can.

When compiling with mlkit, it fails and prints "operand type mismatch for push".  It's failing both on mlkit v4.5.1 and on the current master branch (df67b2f1).

This bug brought to you by Xsmith.

**Comment by willghatch** [comment]
I've only really just begun fuzzing SML, but in a short fuzzing run I actually get crashes with that same message a lot, so I could probably minimize a couple of other programs that do the same thing if you're interested.

**Comment by melsman** [comment]
Thanks for the report. It is valuable; I'll look into the error(s) soon...

ons. 14. jul. 2021 kl. 17.43 skrev William G Hatch ***@***.***

**Comment by willghatch** [comment]
Thanks.  Also, the comment above wasn't meant to rush you, I understand you probably have plenty of other things to worry about besides MLKit fuzzing bugs. :)

**Comment by melsman** [comment]
This error is caused by X86_64 not supporting direct pushes of large immediate constants (those that do not fit in 32 bits).
