### ISSUE TITLE
Discussions?

### ISSUE THREAD

**Issue by bentxt** [melsman/mlkit#93]
Hi
I'm interested in mlkit (and SML in general)  not because of an academic background, but because of hopefully practical reasons like:
- sml in general being a simpler Ocaml
- Concurrent ML
- "regions" of the mlkit implementation
- the js backend of mlkit

Thanks to the standardisation of SML there are more or less compatible alternative implementations, with each having a somewhat different focus. So we have the interesting features of mlkit in this particular case, but then also the interesting situation where it  is possible to compare all these other SML compilers.

The problem: There is no way to have any discussion whatsoever. I find this very unfortunate, since there is much potential and interesting stuff. The whole "regions" part of mlkit for example: So interesting, but for me almost impossible to access. I'm familiar with the paper, but I'm a user and not a scientist.

So do you see this as a problem? Do you have any idea what a solution could be? 

What do you think of having a discussion section here on your github?

What is your opinion an a SML discord channel, would you visit it something like that?

Thank you very much for any answer.
Ben

**Comment by Munksgaard** [comment]
> What is your opinion an a SML discord channel, would you visit it something like that?

For the record, there is both a [subreddit](https://reddit.com/r/sml) and an IRC channel (#sml at libera.chat). The IRC channel does not see a lot of activity, but my impression is that the subreddit sees a fair bit of action.

**Comment by melsman** [comment]
You are making a good point, Ben! I would be happy to discuss SML related
issues, including the issues about the topics you mention, on any platform
where such issues are raised. Personally, I have been reluctant to
participate in too many discussions about how SML should be changed, as
such discussions tend to split the community rather than uniting it. But
when it comes to implementation techniques, standardisation of libraries,
package management, tooling, etc, I would be happy to discuss...

ons. 12. jan. 2022 kl. 12.13 skrev Philip Munksgaard <
***@***.***>:

**Comment by melsman** [comment]
I have opened for discussions at the github repository and send out an announcement...

**Comment by bentxt** [comment]
Thanks alot for your quick reply. Thanks for opening the discussion section here on github. 

> For the record, there is both a subreddit and an IRC channel (#sml at libera.chat). The IRC channel does not see a lot of activity, but my impression is that there is some discussion on the subreddit.

A lot of people and programming projects use discord (https://discord.com), which is a somewhere between a chat and a forum. It's free and the setup is very quick. Would you participate in such a medium, if I invited you?

**Comment by eatonphil** [comment]
+1 about reddit.com/r/sml. It is the most active SML community I know of.

**Comment by Munksgaard** [comment]
> A lot of people and programming projects use discord (https://discord.com), which is a somewhere between a chat and a forum. It's free and the setup is very quick. Would you participate in such a medium, if I invited you?

I'm not opposed to it, but I'm a little worried about splitting an already small community more than necessary. I guess you could try and post it on the subreddit and see what happens :)

**Comment by bentxt** [comment]
The reason I'm a little hesitant to post on r/sml lies in the way I see it used by the sml community: As a news site to post exciting news on the subject or ignite interesting conversations to the astute and experienced sml user. So I have doubts whether my basic and mundane topics are more than a nuisance. 

Maybe I give it a try and ask a question.
